name: Update Schema

on:
  push:
    branches: [main]
    paths:
      - "servers/attio/src/lib/scopes/**"
      - "servers/attio/scripts/extract-tools-schema.ts"
      - ".github/workflows/update-schema.yml"
  workflow_dispatch:

env:
  PAT_TOKEN: ${{ secrets.GO_PRIVATE_MODULES }}

jobs:
  update-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Generate schema
        run: |
          cd servers/attio
          pnpm generate:schema

      - name: Download and install trunk manually
        run: |
          curl -fsSL https://trunk.io/releases/trunk -o /tmp/trunk
          chmod +x /tmp/trunk
          echo "TRUNK_PATH=/tmp/trunk" >> $GITHUB_ENV

      - name: Initialize trunk in repository (if needed)
        run: |
          if [ ! -f .trunk/trunk.yaml ]; then
            $TRUNK_PATH init --ci
          fi

      - name: Format generated schema with trunk
        run: |
          $TRUNK_PATH fmt servers/attio/tools-schema.json || true

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet servers/attio/tools-schema.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes to community-mcp
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add servers/attio/tools-schema.json
          git commit -m "chore: update tools schema [skip ci]"
          git push

    outputs:
      changes: ${{ steps.check_changes.outputs.changes }}

  update-hypermode-repo:
    needs: update-schema
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout community-mcp repo
        uses: actions/checkout@v4
        with:
          repository: hypermodeinc/community-mcp
          token: ${{ secrets.GITHUB_TOKEN }}
          path: community-mcp

      - name: Checkout hypermode repo
        uses: actions/checkout@v4
        with:
          repository: hypermodeinc/hypermode
          ref: main
          token: ${{ env.PAT_TOKEN }}
          path: hypermode

      - name: Copy schema file and check for differences
        id: sync_check
        run: |
          cp community-mcp/servers/attio/tools-schema.json hypermode/seeds/attio_tools.json
          cd hypermode
          if git diff --quiet seeds/attio_tools.json; then
            echo "sync_needed=false" >> $GITHUB_OUTPUT
            echo "No changes needed - files are in sync"
          else
            echo "sync_needed=true" >> $GITHUB_OUTPUT
            echo "Changes detected - sync needed"
            git diff seeds/attio_tools.json
          fi

      - name: Create Pull Request in hypermode repo
        if: steps.sync_check.outputs.sync_needed == 'true'
        run: |
          cd hypermode

          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Create and switch to new branch
          git checkout -b update-attio-schema

          # Add and commit changes
          git add seeds/attio_tools.json
          git commit -m "chore: update Attio tools schema from community-mcp"

          # Push the branch
          git push origin update-attio-schema

          # Create PR using GitHub CLI
          gh pr create \
            --title "Update Attio tools schema" \
            --body "🤖 **Automated PR**: This PR updates the Attio tools schema in \`seeds/attio_tools.json\` with the latest version from the community-mcp repository.

          ## ⚠️ Important: Manual Steps Required Before Merging

          **You must run database migrations before merging this PR:**

          \`\`\`bash
          # Run the migrations to update the database schema
          pnpm run migrate
          # or whatever your migration command is
          \`\`\`

          The schema changes may include new tables, columns, or other database structure updates that require migration execution.

          ## Changes
          - 📝 Updated \`seeds/attio_tools.json\` with latest schema from community-mcp

          ## Source Information
          - 🔗 Generated from: \`hypermodeinc/community-mcp/servers/attio/tools-schema.json\`
          - 🚀 Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          - 📅 Generated at: ${{ github.event.head_commit.timestamp }}

          ---

          ⚡ This PR was automatically created by the schema update workflow. Please review the changes and run migrations before merging." \
            --head update-attio-schema \
            --base main
        env:
          GH_TOKEN: ${{ env.PAT_TOKEN }}
